# Add comment related to interrupts action on new issues.
issueOpened: >
  Thank you for opening an issue. Our team's interrupts engineer will review your issue shortly.
  
   **Issue Resolution:**
   - [ ] _[Interrupts Engineer]_  Triage / apply categorization labels
   - [ ] _[Interrupts Engineer]_ Verify / Reproduce the reported issue
   - [ ] _[Forseti Engineer]_ Perform root cause analysis
   - [ ] _Forseti Engineer]_ Add tasks and next steps to resolve this issue.

#pullRequestOpened: >
#  Thank you for raising your pull request.
