coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        enabled: yes
        threshold: 1%
      patch:
        enabled: yes
        threshold: 1%
comment:
  layout: "header, diff, tree, changes"
  behavior: default
  require_changes: yes
