# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import explain_pb2 as explain__pb2


class ExplainStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/iam.Explain/Ping',
        request_serializer=explain__pb2.PingRequest.SerializeToString,
        response_deserializer=explain__pb2.PingReply.FromString,
        )


class ExplainServicer(object):

  def Ping(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExplainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=explain__pb2.PingRequest.FromString,
          response_serializer=explain__pb2.PingReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iam.Explain', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
