apiVersion: v1
kind: Service
metadata:
  name: cloudsqlproxy
  labels:
    app: cloudsqlproxy
spec:
  ports:
    - port: 3306
      protocol: TCP
  clusterIP: ${CLOUDSQL_IP}
  selector:
    app: cloudsqlproxy