apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: forseti
spec:
  schedule: "${CRON_SCHEDULE}"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: server-credentials
          containers:
            - name: forseti
              image: ${FORSETI_IMAGE}
              command: ["/forseti-security/install/scripts/docker_entrypoint.sh",
                        "--bucket", "${BUCKET}",
                        "--log_level", "debug",
                        "--run_server",
                        "--services", "scanner model inventory explain notifier",
                        "--run_cronjob" ]
              securityContext:
                runAsUser: 0  # root user
                allowPrivilegeEscalation: true
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
                  readOnly: true
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
          restartPolicy: Never
      completions: 1
  concurrencyPolicy: Forbid
