apiVersion: apps/v1
kind: Deployment
metadata:
  name: forseti-server
spec:
  selector:
    matchLabels:
      app: forseti-server
  replicas: 1
  template:
    metadata:
      labels:
        app: forseti-server
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: server-credentials
      containers:
        - name: forseti-server
          image: ${FORSETI_IMAGE}
          ports:
            - containerPort: 50051
          command: ["/forseti-security/install/scripts/docker_entrypoint.sh",
                    "--bucket", "${SERVER_BUCKET}",
                    "--log_level", "debug",
                    "--run_server",
                    "--services", "scanner model inventory explain notifier",
                    "--cron_schedule", "${CRON_SCHEDULE}"]
          securityContext:
            runAsUser: 0  # root user. TODO non-root as soon as practical
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
