#!/bin/bash
# Copyright 2017 The Forseti Security Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generate an inverted index (represented as a YAML map) of files=>versions
# present.

function silent_pushd() {
    pushd $1 1>/dev/null 2>&1
}

function silent_popd() {
    popd 1>/dev/null 2>&1
}

function all_version_directories_except_latest() {
    find _docs -mindepth 1 -maxdepth 1 -not -path */_latest -type d
}

#######################################
# Get list of all version names from 
# docs
#
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Newline-separated list of version
#   names
#######################################
function all_versions() {
    local version_directories
    version_directories="$(all_version_directories_except_latest)"

    for version_directory in ${version_directories}; do
        local version
        version="$(basename "${version_directory}")"

        printf "$version\n"
    done
}

function latest_version_files() {
    silent_pushd _docs/_latest
        find . -type f
    silent_popd
}

function all_version_files() {
    for dir in $(all_version_directories_except_latest); do
    silent_pushd $dir
        find . -type f
    silent_popd
    done 
}

function set_union_of_all_version_files() {
    all_version_files | sort | uniq
}

#######################################
# Builds an inverted index in YAML that
# represents all the versions a doc
# belongs to.
#
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
function build_doc_version_index() {
    > _data/doc_versions.yml
    echo "# Auto-generated by ./scripts/build_doc_version_index.sh" \
        >> _data/doc_versions.yml
    echo "# DO NOT MODIFY" >> _data/doc_versions.yml

    local versions
    versions="$(all_versions | sort -rV)"

    for version in ${versions}; do
        printf -- "- ${version}\n" >> _data/doc_versions.yml
    done

    > _data/doc_version_index.yml
    echo "# Auto-generated by ./scripts/build_doc_version_index.sh" \
        >> _data/doc_version_index.yml
    echo "# DO NOT MODIFY" >> _data/doc_version_index.yml

    for file in $(set_union_of_all_version_files); do
        local filename="${file#./}"
        printf "${filename}:\n" >> _data/doc_version_index.yml

        for version in $versions; do
            local version_filename="_docs/${version}/${filename}"
            if [ -f "${version_filename}" ]; then
                printf -- "- ${version}\n" >> _data/doc_version_index.yml
            fi
        done
    done
}

function main() {
    build_doc_version_index
}

main "$@"
