#!/bin/bash
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A git pre-commit hook to perform linter checks to catch errors locally

# Check if the user is in a virtual environment
if [ -z $VIRTUAL_ENV ]; then
	echo "Need to be in a virtual env"
	exit 1
fi

# Check if pylintrc exists and user is in the top repository directory
if [ ! -e "./pylintrc" ]; then
	echo "You must commit from top repository directory"
	exit 1
fi

echo "Executing pylint..."
pylint --rcfile=pylintrc --ignore-patterns=".*_test.*,.*test_.*,.*test.py,.*pb2.*" --output-format=text google || exit 1

echo "Executing tests..."
python setup.py google_test --test-dir tests/
