# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import playground_pb2 as playground__pb2


class PlaygroundStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/Ping',
        request_serializer=playground__pb2.PingRequest.SerializeToString,
        response_deserializer=playground__pb2.PingReply.FromString,
        )
    self.SetIamPolicy = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/SetIamPolicy',
        request_serializer=playground__pb2.SetIamPolicyRequest.SerializeToString,
        response_deserializer=playground__pb2.SetIamPolicyReply.FromString,
        )
    self.GetIamPolicy = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/GetIamPolicy',
        request_serializer=playground__pb2.GetIamPolicyRequest.SerializeToString,
        response_deserializer=playground__pb2.GetIamPolicyReply.FromString,
        )
    self.CheckIamPolicy = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/CheckIamPolicy',
        request_serializer=playground__pb2.CheckIamPolicyRequest.SerializeToString,
        response_deserializer=playground__pb2.CheckIamPolicyReply.FromString,
        )
    self.AddMember = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/AddMember',
        request_serializer=playground__pb2.AddMemberRequest.SerializeToString,
        response_deserializer=playground__pb2.AddMemberReply.FromString,
        )
    self.CreateMember = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/CreateMember',
        request_serializer=playground__pb2.CreateMemberRequest.SerializeToString,
        response_deserializer=playground__pb2.CreateMemberReply.FromString,
        )
    self.DeleteMember = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/DeleteMember',
        request_serializer=playground__pb2.DeleteMemberRequest.SerializeToString,
        response_deserializer=playground__pb2.DeleteMemberReply.FromString,
        )
    self.AddResource = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/AddResource',
        request_serializer=playground__pb2.AddResourceRequest.SerializeToString,
        response_deserializer=playground__pb2.AddResourceReply.FromString,
        )
    self.DeleteResource = channel.unary_unary(
        '/google.cloud.security.iam.playground.Playground/DeleteResource',
        request_serializer=playground__pb2.DeleteResourceRequest.SerializeToString,
        response_deserializer=playground__pb2.DeleteResourceReply.FromString,
        )


class PlaygroundServicer(object):

  def Ping(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetIamPolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIamPolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckIamPolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMember(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateMember(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteMember(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddResource(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteResource(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlaygroundServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=playground__pb2.PingRequest.FromString,
          response_serializer=playground__pb2.PingReply.SerializeToString,
      ),
      'SetIamPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.SetIamPolicy,
          request_deserializer=playground__pb2.SetIamPolicyRequest.FromString,
          response_serializer=playground__pb2.SetIamPolicyReply.SerializeToString,
      ),
      'GetIamPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.GetIamPolicy,
          request_deserializer=playground__pb2.GetIamPolicyRequest.FromString,
          response_serializer=playground__pb2.GetIamPolicyReply.SerializeToString,
      ),
      'CheckIamPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.CheckIamPolicy,
          request_deserializer=playground__pb2.CheckIamPolicyRequest.FromString,
          response_serializer=playground__pb2.CheckIamPolicyReply.SerializeToString,
      ),
      'AddMember': grpc.unary_unary_rpc_method_handler(
          servicer.AddMember,
          request_deserializer=playground__pb2.AddMemberRequest.FromString,
          response_serializer=playground__pb2.AddMemberReply.SerializeToString,
      ),
      'CreateMember': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMember,
          request_deserializer=playground__pb2.CreateMemberRequest.FromString,
          response_serializer=playground__pb2.CreateMemberReply.SerializeToString,
      ),
      'DeleteMember': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteMember,
          request_deserializer=playground__pb2.DeleteMemberRequest.FromString,
          response_serializer=playground__pb2.DeleteMemberReply.SerializeToString,
      ),
      'AddResource': grpc.unary_unary_rpc_method_handler(
          servicer.AddResource,
          request_deserializer=playground__pb2.AddResourceRequest.FromString,
          response_serializer=playground__pb2.AddResourceReply.SerializeToString,
      ),
      'DeleteResource': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteResource,
          request_deserializer=playground__pb2.DeleteResourceRequest.FromString,
          response_serializer=playground__pb2.DeleteResourceReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.cloud.security.iam.playground.Playground', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
